BlueROV:
{
    mass: 13.5; # kg
    buoyancy: -132.435;  # Correct buoyancy = -13.5 * 9.81
    center_of_gravity: [0.0, 0.0, 0.0]; # x, y, z coordinates
    inertia_tensor: [0.26, 0.23, 0.37]; # kg*m^2
    gravity_vector: [0.0, 0.0, -9.81]; # m/s^2
    center_of_buoyancy: [0.0, 0.0, 0.0]; # x, y, z coordinates

    added_mass: [-6.36, -7.12, -18.68, -0.189, -0.135, -0.222]; # kg

    # Damping coefficients
    damping_coefficients_linear:[13.7, 0.0, 33.0, 0.0, 0.8, 0.0]; # Ns/m
    damping_coefficients_quadratic: [141.0, 217.0, 190.0, 1.19, 0.47, 1.5]; # Ns/m

    thruster_positions: [
        0.134,  -0.134,  0.085,   # T1
        0.134, 0.134,  0.085,   # T2
        -0.134,  -0.134,  0.085,   # T3
        -0.134, 0.134,  0.085,   # T4

        0.218,  -0.218,  0.0,     # T5
        0.218, 0.218,  0.0,     # T6
        -0.218,  -0.218,  0.0,     # T7
        -0.218, 0.218,  0.0      # T8
    ];

    thruster_orientations_degrees: [
    0.0,  0.0,  45.0,   # T1
    0.0,  0.0,   -45.0,   # T2
    0.0,  0.0, 315.0,   # T3
    0.0,  0.0,  -315.0,   # T4

    0.0,  -90.0,   0.0,   # T5 : +x -> -z
    0.0, -90.0,   0.0,   # T6 : +x -> +z
    0.0, -90.0,   0.0,   # T7 : +x -> +z
    0.0,  -90.0,   0.0    # T8 : +x -> -z
];

};
